prefix = "."
stop-words = "stopwords.txt"

dataset = "data"
corpus = "line.toml"
index = "idx"



[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

[query-runner]
query-path = "movies_sample_queries.txt"
query-id-start = 1

